### PR TITLE
Bottom Nav Enhancement

### PR DESCRIPTION
**Pull request by essy16**
## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

Screen Shot 2023-06-05 at 8 59 51 PM

### CODE REVIEW

**Comment by Suryansh1720001** [comment]
@essy16 
The application screenshot is unclear. Can you please provide a better-quality screenshot and a demo video?

**Comment by essy16** [comment]
A video of the code ?

**Comment by Suryansh1720001** [comment]
Video of the application

**Comment by essy16** [comment]
https://github.com/Suryansh1720001/Taaveez/assets/58663564/3d52c377-175d-4cb6-9513-92faddab72f3

**Comment by Suryansh1720001** [comment]
Hello @essy16 
The bottom navigation is not properly aligned and the styling needs improvement. Please suggest an alternative solution or I will close the pull request in two days. Please update me accordingly.
Thank You

**Comment by essy16** [comment]
> Hello @essy16 
> 
> The bottom navigation is not properly aligned and the styling needs improvement. Please suggest an alternative solution or I will close the pull request in two days. Please update me accordingly.
> 
> Thank You
How do you want it to be aligned and styled ?

**Comment by Suryansh1720001** [comment]
@essy16
Please improve the style, and ensure that the bottom navigation is aligned at the bottom properly, rather than being positioned above it.

**Comment by Suryansh1720001** [comment]
To be frank, I find the current design rather unappealing. I must express my preference for the previous design, which I found to be more attractive. I apologize for the inconvenience, but I kindly request that you redefine the current design to align with the theme of the previous iteration. Regrettably, I do not possess a screenshot of the previous design.
Additionally, I have a suggestion for you. I recommend utilizing the previous design without incorporating a color change option for the item. Instead, consider implementing two types of items. The first type would be a simple item that is readily available within the application. The second type would be a detailed view item, which allows users to view a portion of the content. To achieve this, you can adopt the concept of invisible/visible views commonly used in Android development. The two types of items can be accessed through a pop-up menu, offering the options of "Normal View" and "Detailed View".

**Pull request closed without merging**
