### PR TITLE
Additions in issue template done

### LINKED ISSUE #54: Addition in Issue Template
## Description:

*I noticed that the repository does not have an appropriate issue template.*

*Issue Template: I want to add  some more points to your issue template like styling changes, config.yml for all other issues etc*

Please assign this issue to me under Gssoc'23 @Suryansh1720001 

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by Anshika-Jain02**
## Fixes Issue

Closes #54 

## Changes proposed
Two files are added in ISSUE_TEMPLATE:-
- style.yml
- docs.yml

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

@Suryansh1720001 Thank you for this opportunity :)

### CODE REVIEW

**Comment by Vaibhav2002** [comment]
@Anshika-Jain02 please attach a screenshot of how the issue template looked before and how it looks now

**Comment by Anshika-Jain02** [comment]
@Vaibhav2002 

## Before ( styles.yml and docs.yml doesn't exist )
taavez issue template

## After 
- style.yml
taavez issue template 1

- docs.yml

https://github.com/Taaveez/Taaveez-android/assets/104912087/5f810302-a6d1-4b2a-92f1-b009e5d88fea

**Review by Vaibhav2002 — APPROVED** [review]
LGTM!

**Comment by Suryansh1720001** [comment]
Closed as Completed 
Issue - #54

**Pull request merged**
