### PR TITLE
Fix : Updated Versions of dependencies

### PR DESCRIPTION
**Pull request by DevMehta1206**
## Check List (Check all the applicable boxes) 

- [ ] My code follows the code style of this project.
- [ ] All new and existing tests passed.
- [ ] This PR does not contain plagiarized content.
- [ ] The title of my pull request is a short description of the requested changes.

## Note to reviewers
@Vaibhav2002  please review the changes I have made. fixed the issue that was arriving wile the apk build time

update all the versions of the dependencies 
added multidex support

### CODE REVIEW

**Comment by DevMehta1206** [comment]
@Suryansh1720001 please have a look at this. I have updated all the versions

**Review by Vaibhav2002 — APPROVED** [review]

**Comment by Vaibhav2002** [comment]
@DevMehta1206 from now on, please mention the issue number in the PR like this, so the issue gets closed on merge
Fixes #65

**Comment by Suryansh1720001** [comment]
@DevMehta1206 
Plz, squash the commit into a single commit.

**Comment by DevMehta1206** [comment]
@Suryansh1720001 please use squash and merge button present there

**Comment by Suryansh1720001** [comment]
Issue #65 Completed

**Pull request merged**
